# Generated by Django 2.1.7 on 2019-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190227_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='Back_img',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='Company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='Curosal1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='Curosal2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='News_img',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='News_title',
            field=models.CharField(max_length=200),
        ),
    ]
