# Generated by Django 2.1.7 on 2019-02-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190227_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='HEAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_link', models.CharField(max_length=200)),
                ('Login_link', models.CharField(max_length=200)),
            ],
        ),
    ]
