# Generated by Django 2.1.7 on 2019-02-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUTUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_us', models.CharField(max_length=2000)),
                ('Aim', models.CharField(max_length=200)),
                ('Content', models.CharField(max_length=2000)),
                ('Image', models.CharField(max_length=100)),
                ('Developer', models.CharField(max_length=400)),
            ],
        ),
    ]
