# Generated by Django 2.1.7 on 2019-02-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOOTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disclaimer', models.CharField(max_length=2000)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Facebook', models.CharField(max_length=50)),
                ('Twitter', models.CharField(max_length=50)),
                ('Google', models.CharField(max_length=50)),
                ('Instagram', models.CharField(max_length=50)),
                ('Terms', models.CharField(max_length=1000)),
            ],
        ),
    ]
