# Generated by Django 2.1.7 on 2019-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_no', models.CharField(max_length=20)),
                ('Heading', models.CharField(max_length=1000)),
                ('Description', models.CharField(max_length=4000)),
                ('User', models.CharField(max_length=100)),
                ('Time_date', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
    ]
