# Generated by Django 2.1.7 on 2019-02-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190227_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='REGISTER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
                ('Institution', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('OTP', models.CharField(max_length=20)),
            ],
        ),
    ]
