# Generated by Django 2.1.7 on 2019-02-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_heading', models.CharField(max_length=10000)),
                ('slider_caption', models.CharField(max_length=10000)),
                ('image_link', models.CharField(max_length=10000)),
                ('heading', models.CharField(max_length=10000)),
                ('image1_link', models.CharField(max_length=10000)),
                ('contents', models.CharField(default='SOME STRING', max_length=10000)),
            ],
        ),
    ]
