# Generated by Django 2.1.7 on 2019-02-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(max_length=10000)),
                ('dislikes', models.IntegerField(max_length=10000)),
                ('reports', models.IntegerField(max_length=10000)),
                ('tags', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(max_length=10000)),
                ('dislikes', models.IntegerField(max_length=10000)),
                ('reports', models.IntegerField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100000)),
                ('Answer', models.CharField(max_length=10000000)),
                ('likes', models.IntegerField(max_length=10000)),
                ('dislikes', models.IntegerField(max_length=10000)),
                ('reports', models.IntegerField(max_length=10000)),
                ('tags', models.CharField(max_length=1000000)),
            ],
        ),
    ]
